# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-19 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelog',
            name='log_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'On Save'), (0, 'On Update'), (0, 'On Sync')], default=0),
        ),
    ]
